from django import forms
from .models import Project

# class ProjectForm(forms.ModelForm):
#     class Meta:
#         model = Project
#         fields = '__all__'
#         widgets = {
#             'start_date': forms.DateInput(attrs={'type': 'date'}),
#             'end_date': forms.DateInput(attrs={'type': 'date'}),
#         }
from django import forms
from .models import Project

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['code', 'name', 'location', 'total_budget', 'start_date', 'end_date', 'notes']
        widgets = {
            # 'code': forms.TextInput(attrs={'class': 'form-control'}),
            'code': forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'location': forms.TextInput(attrs={'class': 'form-control'}),
            'total_budget': forms.NumberInput(attrs={'class': 'form-control'}),
            'start_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'end_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'notes': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['code'].required = False  # Let view handle it



# forms.py
from django import forms
from .models import Transaction

class TransactionForm(forms.ModelForm):
    created_at = forms.DateTimeField(
        required=False,
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
         input_formats=['%Y-%m-%dT%H:%M'] 
    )

    class Meta:
        model = Transaction
        fields = ['transaction_id', 'project', 'type', 'amount', 'vendor', 'status', 'category', 'description', 'created_at']
    def __init__(self, *args, **kwargs):
        super(TransactionForm, self).__init__(*args, **kwargs)

        # Add placeholders or empty labels for select fields
        self.fields['project'].empty_label = "Select Project"
        self.fields['type'].empty_label = "Select Type"
        self.fields['status'].empty_label = "Select Status"
        self.fields['category'].empty_label = "Select Category"

        # Optional: add placeholder for other text fields
        self.fields['vendor'].widget.attrs.update({'placeholder': 'Enter vendor name'})
        self.fields['description'].widget.attrs.update({'placeholder': 'Enter description'})


from django import forms
from .models import Staff,Loan
from django import forms
from .models import Staff

class StaffForm(forms.ModelForm):
    class Meta:
        model = Staff
        fields = ['staff_id', 'name', 'photo', 'designation', 'department', 'project', 'salary', 'date_of_join']
        labels = {
            'staff_id': 'Staff ID',
            'name': 'Full Name',
            'photo': 'Photo',
            'designation': 'Designation',
            'department': 'Department',
            'project': 'Project Assigned',
            'salary': 'Monthly Salary',
            'date_of_join': 'Date of Joining',
        }
        widgets = {
            'staff_id': forms.TextInput(attrs={
    'class': 'form-control',
    'placeholder': 'Autogenerated Staff ID',
    'readonly': 'readonly',    # Prevent editing
    'id': 'staff_id'           # Needed for JS
}),

            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter full name'
            }),
            'photo': forms.ClearableFileInput(attrs={
                'class': 'form-control'
            }),
            'designation': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter designation (e.g., Manager)'
            }),
            'department': forms.TextInput(attrs={  # ✅ This is a text field
    'class': 'form-control',
    'placeholder': 'Enter department name'
}),

            'project': forms.Select(attrs={
                'class': 'form-select'
            }),
            'salary': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter salary amount'
            }),
            'date_of_join': forms.DateInput(attrs={
                'type': 'date',
                'class': 'form-control'
            }),
        }
    def __init__(self, *args, **kwargs):
        super(StaffForm, self).__init__(*args, **kwargs)
        self.fields['project'].empty_label = "Select Project"

from django import forms
from .models import Loan

from django import forms
from .models import Loan

class LoanForm(forms.ModelForm):
    class Meta:
        model = Loan
        exclude = ('created_at', 'updated_at')
        widgets = {
            'loan_id': forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}),
            'project': forms.Select(attrs={'class': 'form-select'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'interest_rate': forms.NumberInput(attrs={'class': 'form-control'}),
            'payment_proof': forms.FileInput(attrs={'class': 'form-control'}),
            'loan_purpose': forms.TextInput(attrs={'class': 'form-control'}),
            'start_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['project'].empty_label = "Select Project"

        # ✅ Auto-generate loan_id only if it's a new loan
        if not self.instance.pk:
            last_loan = Loan.objects.order_by('-id').first()
            next_number = 1 if not last_loan else last_loan.id + 1
            self.fields['loan_id'].initial = f"LOAN-{next_number:04d}"


# forms.py
from django import forms
from .models import Repayment
from django import forms
from .models import Repayment
from django import forms
from .models import Repayment

class RepaymentForm(forms.ModelForm):
    class Meta:
        model = Repayment
        fields = ['date', 'amount_paid', 'photo_proof']  # added photo_proof
        labels = {
            'date': 'Repayment Date',
            'amount_paid': 'Amount Paid (₹)',
            'photo_proof': 'Photo Proof',  # optional label
        }
        widgets = {
            'date': forms.DateInput(attrs={
                'type': 'date',
                'class': 'form-control',
                'placeholder': 'Select repayment date'
            }),
            'amount_paid': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter amount paid'
            }),
            'photo_proof': forms.ClearableFileInput(attrs={
                'class': 'form-control',
                'accept': 'image/*',
            }),
        }


from django import forms
from .models import Task
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['task_id', 'date', 'staff', 'project', 'description','voice_memo','due_date']
        labels = {
            'task_id': 'Task ID',
            'date': 'Task Date',
            'staff': 'Assigned Staff',
            'project': 'Related Project',
            'description': 'Task Description',
            'voice_memo': 'Voice Memo (optional)',
        }
        widgets = {
            'task_id': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter unique task ID'
            }),
            'date': forms.DateInput(attrs={
                'type': 'date',
                'class': 'form-control'
            }),
            'due_date': forms.DateInput(attrs={
                'type': 'date',
                'class': 'form-control'
            }),
            'staff': forms.Select(attrs={
                'class': 'form-select'
            }),
            'project': forms.Select(attrs={
                'class': 'form-select'
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 4,
                'placeholder': 'Enter task details or instructions'
            }),
             'voice_memo': forms.ClearableFileInput(attrs={
                'class': 'form-control',
                'accept': 'audio/*'
            }),
        }

# Just use a plain file input in HTML instead of this:
# class TaskFileForm(forms.ModelForm):
#     class Meta:
#         model = TaskFile
#         fields = ['file']



# forms.py

from django import forms
from .models import StaffMessage

class StaffMessageForm(forms.ModelForm):
    class Meta:
        model = StaffMessage
        fields = ['message']
        widgets = {
            'message': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter your message here...', 'rows': 4}),
        }



from django import forms
from .models import Target
from django import forms
from .models import Target

class TargetForm(forms.ModelForm):
    class Meta:
        model = Target
        fields = ['date', 'project', 'staff', 'target_amount', 'notes']
        widgets = {
            'date': forms.DateInput(attrs={
                'type': 'date',
                'class': 'form-control',
                'placeholder': 'Select target date'
            }),
            'project': forms.Select(attrs={
                'class': 'form-select'
            }),
            'staff': forms.Select(attrs={
                'class': 'form-select'
            }),
            'target_amount': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter target amount'
            }),
            'notes': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3,
                'placeholder': 'Enter notes (optional)'
            }),
        }

    def __init__(self, *args, **kwargs):
        super(TargetForm, self).__init__(*args, **kwargs)
        self.fields['project'].empty_label = "Select Project"
        self.fields['staff'].empty_label = "Select Staff"


from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your username'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your password'
    }))



from .models import LeaveRequest

from django import forms
from app1.models import LeaveRequest

class LeaveRequestForm(forms.ModelForm):
    class Meta:
        model = LeaveRequest
        fields = ['purpose', 'start_date', 'end_date', 'reason']
        widgets = {
            'purpose': forms.Select(attrs={'class': 'form-select'}),
            'start_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'end_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'reason': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
        }



# forms.py
from django import forms
from .models import Target

class TargetAchievementForm(forms.ModelForm):
    class Meta:
        model = Target
        fields = ['achieved_amount']
        widgets = {
            'achieved_amount': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter achievement amount'}),
        }
