# Generated by Django 5.2.3 on 2025-06-12 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_category_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='vendor_client',
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.project'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='Approved', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=50),
        ),
    ]
