# Generated by Django 5.2.3 on 2025-06-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_loan_loan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='achieved_amount',
        ),
        migrations.RemoveField(
            model_name='target',
            name='status',
        ),
    ]
