# Generated by Django 5.2.3 on 2025-06-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_target_achieved_amount_remove_target_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
