# Generated by Django 5.2.3 on 2025-06-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_loan_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='Annual Interest in %', max_digits=5),
        ),
    ]
