# Generated by Django 5.2.3 on 2025-06-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='annual Interest in %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
