# Generated by Django 5.2.3 on 2025-06-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_loan_interest_rate_alter_loan_loan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='photo_proof',
            field=models.ImageField(blank=True, null=True, upload_to='repayment_proofs/'),
        ),
    ]
