# Generated by Django 5.2.3 on 2025-06-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_repayment_photo_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateField(),
        ),
    ]
