# Generated by Django 5.2.3 on 2025-06-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='loan_payment_proofs/'),
        ),
    ]
