# Generated by Django 5.2.3 on 2025-06-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_loan_payment_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
